cd PAPER-SERVER
cd plugins
wget https://ci.viaversion.com/job/ViaVersion/797/artifact/build/libs/ViaVersion-4.9.3.jar
wget https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/4.9.2/PAPER/ViaBackwards-4.9.2.jar
wget https://hangarcdn.papermc.io/plugins/ViaVersion/ViaRewind/versions/3.0.6/PAPER/ViaRewind-3.0.6.jar
wget https://hangarcdn.papermc.io/plugins/ViaVersion/ViaRewindLegacySupport/versions/1.4.2/PAPER/viarewind-legacy-support-1.4.2.jar
wget https://hangarcdn.papermc.io/plugins/Artillex-Studios/AxSmithing/versions/1.6/PAPER/AxSmithing-1.6-all.jar
wget https://github.com/HideTheMonkey/EventLoggerForIM/releases/download/2.1.1/ELFIM-2.1.1.jar
wget https://hangarcdn.papermc.io/plugins/HelpChat/PlaceholderAPI/versions/2.11.5/PAPER/PlaceholderAPI-2.11.5.jar
wget https://hangarcdn.papermc.io/plugins/Ronan/BetterRTP/versions/3.6.8/PAPER/BetterRTP-3.6.8.jar
wget https://cdn.modrinth.com/data/Z5ayyqQS/versions/j99AScYl/EpicGuardPaper-7.6.0.jar
wget https://hangarcdn.papermc.io/plugins/Collagen/Backuper/versions/1.6.1b/PAPER/Backuper-1.6.1b.jar
wget https://hangarcdn.papermc.io/plugins/LOOHP/InteractionVisualizer/versions/1.18.8/PAPER/InteractionVisualizer-1.18.8.0.jar
wget https://hangarcdn.papermc.io/plugins/Aeltumn/Automated-Crafting/versions/2.6.2/PAPER/AutomatedCrafting-2.6.2.jar
wget https://hangarcdn.papermc.io/plugins/Frogperson/MiniBlocks/versions/3.4.2/PAPER/MiniBlocks-3.4.2.jar
wget https://hangarcdn.papermc.io/plugins/V1ttorassi/TreeFella/versions/1.3/PAPER/TreeFella-1.3.jar
wget https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.21.0-dev+73-2cb0af0.jar
wget https://hangarcdn.papermc.io/plugins/Gecolay/GSit/versions/1.7.0/PAPER/GSit-1.7.0.jar
wget https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/15.0.2/SkinsRestorer.jar
wget https://hangarcdn.papermc.io/plugins/Multiverse/Multiverse-Core/versions/4.3.12/PAPER/multiverse-core-4.3.12.jar
wget https://hangarcdn.papermc.io/plugins/jmp/TabTPS/versions/1.3.22/PAPER/tabtps-spigot-1.3.22.jar
wget https://hangarcdn.papermc.io/plugins/dmulloy2/ProtocolLib/versions/5.1.0/PAPER/ProtocolLib.jar
wget https://cdn.modrinth.com/data/45YNCEXh/versions/tPTD7FJz/BetterMessages-3.3.2.jar
wget https://hangarcdn.papermc.io/plugins/Loving11ish/ClientDetector/versions/2.6.2/PAPER/ClientDetector-2.6.2.jar
wget https://hangarcdn.papermc.io/plugins/Multiverse/Multiverse-Portals/versions/4.2.3/PAPER/multiverse-portals-4.2.3.jar
wget https://hangarcdn.papermc.io/plugins/Mopsy/minecraft_discord_statusbot/versions/13.0/PAPER/Statusbot-13.0-spigot.jar
wget https://hangarcdn.papermc.io/plugins/Niestrat99/ChatPings/versions/2.7/PAPER/ChatPings-2.7.jar
wget https://github.com/Nuckerr/StartUpNotice/releases/download/1.0/StartUpNotice-1.0.jar
wget https://lol.scarsz.me/LvNgHJ/DiscordSRV-Build-1.27.0.jar
cd ..
